### ISSUE TITLE
Initial conditions

### ISSUE THREAD

**Issue by RitzRitzRitz** [develancer/filtfilt#2]
The Matlab implementation of filtfilt() calculates and uses initial conditions that are intended to remove DC offset at the beginning and end of the filtered sequence. Is that also the case for your C++ implementation?

**Comment by develancer** [comment]
I think there is no universal answer on how to deal with such cases. One of the solutions (what I believe Matlab does) is to assume that all the „previous” samples („`x[-1]`” etc.) have the same value as `x[0]`. However, this would not work well in case `x[0]` is different than the “average” DC offset. Another approach would be to detrend the signal prior to processing, but again, simple linear trend may not always be the correct model for a “floating” DC offset.

Therefore, at this moment, the initial conditions are assumed to be zero. However, I might add some additional Matlab-like option in the near future if that's what you need.
